baseurl = "https://memoex.github.io/"
DefaultContentLanguage = "en"
title = "Mr.Blue"
theme = "blue"
metaDataFormat = "yaml"
enableGitInfo = true

[Params]
  subtitle = "Mr.Blue doesn't have a good memory."
  favicon = "favicon.ico"
  sidebar = ["note", "leetcode"]
  comment = true
  disqus = "silverhugh"

[Author]
  name = "Mr.Blue"
  website = "https://memoex.github.io"
  email = "silverhugh.77@gmail.com"
  github = "blue-fatty"

[[menu.main]]
    identifier = "note"
    name = "Note"
    url = "/note/"
    weight = 2

[[menu.main]]
    identifier = "project"
    name = "Project"
    url = "/project/"
    weight = 2

[[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2

[[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3
